export const CREATE_BOARD = 'CREATE_BOARD'
export const GET_ALL_BOARDS_FALSE = 'GET_ALL_BOARDS_FALSE'
export const GET_ALL_BOARDS = 'GET_ALL_BOARDS'
export const GET_DETAIL_BOARD = 'GET_DETAIL_BOARD'
export const SET_LOADING = 'SET_LOADING'
export const UPDATE_BOARD = 'UPDATE_BOARD'

export const SEARCH_USERS = 'SEARCH_USERS'
